#include <SDL.h>

// Map some SDL gamepad buttons to DInput keys

static int sdlGamepadToDirectInputKeyNum[SDL_CONTROLLER_BUTTON_MAX] = {
  0x48, // SDL_CONTROLLER_BUTTON_A -> KP_8
  0x4C, // SDL_CONTROLLER_BUTTON_B -> KP_5
  0x39, // SDL_CONTROLLER_BUTTON_X -> SPACEBAR
  0x2E, // SDL_CONTROLLER_BUTTON_Y -> C
  0x0F, // SDL_CONTROLLER_BUTTON_BACK -> TAB
  0x00, // SDL_CONTROLLER_BUTTON_GUIDE -> None
  0x01, // SDL_CONTROLLER_BUTTON_START -> ESCAPE
  0x00, // SDL_CONTROLLER_BUTTON_LEFTSTICK -> None
  0x00, // SDL_CONTROLLER_BUTTON_RIGHTSTICK -> None
  0x00, // SDL_CONTROLLER_BUTTON_LEFTSHOULDER -> None
  0x1C, // SDL_CONTROLLER_BUTTON_RIGHTSHOULDER -> RETURN
/*
  0xC8, // SDL_CONTROLLER_BUTTON_DPAD_UP -> UP
  0xD0, // SDL_CONTROLLER_BUTTON_DPAD_DOWN -> DOWN
  0xCB, // SDL_CONTROLLER_BUTTON_DPAD_LEFT -> LEFT
  0xCD  // SDL_CONTROLLER_BUTTON_DPAD_RIGHT -> RIGHT
*/

  0x17, // SDL_CONTROLLER_BUTTON_DPAD_UP -> I
  0x24, // SDL_CONTROLLER_BUTTON_DPAD_LEFT -> J
  0x25, // SDL_CONTROLLER_BUTTON_DPAD_DOWN -> K
  0x26  // SDL_CONTROLLER_BUTTON_DPAD_RIGHT -> L
};